bg: Geotrend/bert-base-bg-cased
cs: DeepPavlov/bert-base-bg-cs-pl-ru-cased
da: Maltehb/danish-bert-botxo
de: bert-base-german-cased
el: nlpaueb/bert-base-greek-uncased-v1
en: nlpaueb/legal-bert-base-uncased
es: dccuchile/bert-base-spanish-wwm-cased
et: EMBEDDIA/finest-bert
fi: EMBEDDIA/finest-bert
fr: camembert-base
ga: DCU-NLP/bert-base-irish-cased-v1
hr: bert-base-multilingual-cased
hu: SZTAKI-HLT/hubert-base-cc
it: dbmdz/bert-base-italian-cased
lt: EMBEDDIA/litlat-bert
lv: EMBEDDIA/litlat-bert
mt: bert-base-multilingual-cased
nl: wietsedv/bert-base-dutch-cased
pl: dkleczek/bert-base-polish-cased-v1
pt: neuralmind/bert-base-portuguese-cased
ro: dumitrescustefan/bert-base-romanian-cased-v1
sk: bert-base-multilingual-cased
sl: bert-base-multilingual-cased
sv: KB/bert-base-swedish-cased